name = "basketball-api"
main = "src/basketball-api.js"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production] 
vars = { ENVIRONMENT = "production" }